---
- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /home/circleci/project/backend.tar.gz
    dest: /home/ubuntu/backend/
    owner: ubuntu

- name: Install Node modules
  command: npm install --production
  args:
    chdir: /home/ubuntu/backend
    
- name: Executing node
  become: true
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    pm2 start npm --name "backend" -- run start
  args:
    chdir: /home/ubuntu/backend
