---
- name: Update npm
  become: yes
  shell:
    sudo npm install -g npm@latest

- name: Copy backend dist files to remote server
  unarchive:
    src: /home/circleci/project/backend.tar.gz
    dest: /home/ubuntu

# - name: Install Node modules
#   shell: |
#     cd /home/ubuntu/backend
#     ls -la
#     printenv
#     npm install

# - name: building node services
#   shell: |
#     cd /home/ubuntu/backend
#     npm run build
#     npm run prestart:prod

# - name: "run migrations again"
#   shell: |
#     cd /home/ubuntu/backend
#     npm run migrations
    
# - name: Executing node
#   become: true
#   shell: |
#     cd /home/ubuntu/backend 
#     pm2 start npm --name backend -- start
#     pm2 ls


