---
- name: Update npm
  become: true
  shell:
    sudo npm install -g npm@latest

- name: Copy backend compiled files
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    pwd | ls -l
    cd /home/ubuntu/backend
    npm run build
    pm2 stop default
    pm2 start /home/ubuntu/backend/dist/main.js --name backend