---
- name: Update npm
  become: true
  shell:
    sudo npm install -g npm@latest

- name: Copy backend compiled files
  become: true
  copy:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Executing node
  shell: |
    cd /home/ubuntu/
    pwd
    tar xzvf backend.tar.gz
    cd backend/dist
    pm2 stop default
    pm2 start main.js --name backend