---
- name: Update npm
  become: true
  shell:
    sudo npm install -g npm@latest

- name: Copy backend compiled files
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd backend/dist
    pm2 stop default
    pm2 start main.js --name backend