---
- name: Update npm
  become: true
  shell:
    sudo npm install -g npm@latest

- name: Copy backend compiled files
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "NPM Run Build"
  become: true
  command: ls
  args: 
    chdir: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
