---
- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /home/circleci/project/backend.tar.gz
    dest: /home/ubuntu/backend/
    owner: ubuntu

- name: Install Node modules
  command: npm install --production
  args:
    chdir: /home/ubuntu/backend

- name: "Executing node"
  become: true
  command: 
    pm2 start npm --name udacity-backend -- run start
  args:
    chdir: /home/ubuntu/backend
