version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./frontend/package-lock.json" }}
      - run:
          name: Build front-end
          command: |
            cd ./frontend
            pwd
            node --version
            npm --version
            sudo npm install
            npm run build
      - save_cache:
          paths: [./frontend/node_modules]
          key: frontend-build-{{ checksum "./frontend/package-lock.json" }}
      

  build-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package-lock.json" }}
      - run:
          name: Build back-end
          command: |
            cd ./backend
            pwd
            node --version
            npm --version
            sudo npm install
            npm run build
      - save_cache:
          paths: [./backend/node_modules]
          key: backend-build-{{ checksum "./backend/package-lock.json" }}

  test-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./frontend/package-lock.json" }}
      - run:
          name: Test front-end
          command: |
            cd ./frontend
            pwd
            node --version
            npm --version
            sudo npm install
            npm run test
                
  test-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package-lock.json" }}
      - run:
          name: Test back-end
          command: |
            cd ./backend
            pwd
            node --version
            npm --version
            sudo npm install
            npm run test

  analyze-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./frontend/package-lock.json" }}
      - run:
          name: Analyze front-end
          command: |
            cd ./frontend
            pwd
            node --version
            npm --version
            sudo npm install
            sudo npm audit fix --audit-level=critical

  analyze-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package-lock.json" }}
      - run:
          name: Analyze back-end
          command: |
            cd ./backend
            pwd
            node --version
            npm --version
            sudo npm install
            sudo npm audit fix --audit-level=critical 

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - analyze-frontend:
          requires: [build-frontend]
      - analyze-backend:
          requires: [build-backend]

